config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks', to: 'tasks#create', as: 'create_task'

  get 'tasks', to: 'tasks#index', as: 'tasks'
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:show, :edit, :update, :destroy]
	# resources :tasks
	def index
		@tasks = Task.all
	end

	def destroy
		@task.destroy
		redirect_to tasks_path
	end

	def create
		@task = Task.new(task_params)
		@task.save
		redirect_to task_path(@task)
	end	

	def edit
		@task = Task.find(params[:id])
	end

	def update
		@task = Task.find(params[:id])
		@task.update(task_params)
		redirect_to task_path(@task)
	end

	def new
		@task = Task.new
	end

	def show
		@task = Task.find(params[:id])
	end

	 private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway:600" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form-group">
	<%= form_for(@task) do |f| %>
	  <%= f.label :title %>
	  <%= f.text_field :title %>

	  <%= f.label :details %>
	  <%= f.text_field :details %>

	  <%= f.submit %>
	<% end %>
</div>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="page-title">Your current tasks</h1>
<div class="wrapper">
	<div class="container">
		<h2>All Tasks</h2>
		<% @tasks.each do |task| %>
		<div class="task-list">
		  <p><%= task.title %></p>
		  <p><%= task.details %></p>
		  <p><%= task.completed %></p>
		  <%= link_to "Delete", task_path(task),
		      method: :delete,
		      data: { confirm: "Are you sure?" } %>
		  <% end %>
		</div>
	</div>
</div>

<h3><%= link_to 'Create new Task', new_task_path %></h3>

app/views/tasks/new.html.erb
<h1 class="page-title">Create new Task</h1>

<%= render 'form', task: @task %>

<h3><%= link_to 'Back', tasks_path %></h3>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="page-title">Details</h1>
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Title:"<%= @task.title %>"</h4>
      <p><%= @task.details %></p>
      <hr>
      <% if task.completed == true %>
            <i class="far fa-check-circle"></i>
          <% else %>
             <i class="far fa-circle"></i>
          <% end %>
      <p class="mb-0"><%= @task.completed %></p>
    </div>
</div>

<div class="buttons">
  <a class="link">
    <%= link_to "Edit this task", edit_task_path %>
  </a>

  <div class="link">
    <%= link_to "Back to list", tasks_path %>
  </div>
</div>